// ----------------------------------------------------------------------------------
// Microsoft Developer & Platform Evangelism
// 
// Copyright (c) Microsoft Corporation. All rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
// ----------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: TFSModel.cs
// Generation date: 03/11/2010 08:13:31 p.m.
namespace Microsoft.Samples.DPE.ODataTFS.Model.Entities
{
    /// <summary>
    /// There are no comments for TFSData in the schema.
    /// </summary>
    public partial class TFSData : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TFSData object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TFSData(global::System.Uri serviceRoot) :
            base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Builds in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBuilds(Build build)
        {
            base.AddObject("Builds", build);
        }
        /// <summary>
        /// There are no comments for Changesets in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToChangesets(Changeset changeset)
        {
            base.AddObject("Changesets", changeset);
        }
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
        /// <summary>
        /// There are no comments for WorkItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWorkItems(WorkItem workItem)
        {
            base.AddObject("WorkItems", workItem);
        }
        /// <summary>
        /// There are no comments for Attachments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAttachments(Attachment attachment)
        {
            base.AddObject("Attachments", attachment);
        }
        /// <summary>
        /// There are no comments for Changes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToChanges(Change change)
        {
            base.AddObject("Changes", change);
        }
        /// <summary>
        /// There are no comments for Queries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToQueries(Query query)
        {
            base.AddObject("Queries", query);
        }
        /// <summary>
        /// There are no comments for Branches in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBranches(Branch branch)
        {
            base.AddObject("Branches", branch);
        }
        /// <summary>
        /// There are no comments for AreaPaths in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAreaPaths(AreaPath areaPath)
        {
            base.AddObject("AreaPaths", areaPath);
        }
    }
}
