// ----------------------------------------------------------------------------------
// Microsoft Developer & Platform Evangelism
// 
// Copyright (c) Microsoft Corporation. All rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
// ----------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: TFSModel.cs
// Generation date: 03/11/2010 08:13:31 p.m.
namespace Ordina.TFSMonitor.Model.Entities
{
    /// <summary>
    /// There are no comments for Ordina.TFSMonitor.Model.Entities.WorkItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("WorkItems")]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("ChangedDate", System.Data.Services.Common.SyndicationItemProperty.Updated, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Title", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Description", System.Data.Services.Common.SyndicationItemProperty.Summary, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class WorkItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WorkItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="revision">Initial value of Revision.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="changedDate">Initial value of ChangedDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static WorkItem CreateWorkItem(int ID, int revision, global::System.DateTime createdDate, global::System.DateTime changedDate)
        {
            WorkItem workItem = new WorkItem();
            workItem.Id = ID;
            workItem.Revision = revision;
            workItem.CreatedDate = createdDate;
            workItem.ChangedDate = changedDate;
            return workItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AreaPath in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AreaPath
        {
            get
            {
                return this._AreaPath;
            }
            set
            {
                this.OnAreaPathChanging(value);
                this._AreaPath = value;
                this.OnAreaPathChanged();
                this.OnPropertyChanged("AreaPath");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AreaPath;
        partial void OnAreaPathChanging(string value);
        partial void OnAreaPathChanged();
        /// <summary>
        /// There are no comments for Property IterationPath in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IterationPath
        {
            get
            {
                return this._IterationPath;
            }
            set
            {
                this.OnIterationPathChanging(value);
                this._IterationPath = value;
                this.OnIterationPathChanged();
                this.OnPropertyChanged("IterationPath");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IterationPath;
        partial void OnIterationPathChanging(string value);
        partial void OnIterationPathChanged();
        /// <summary>
        /// There are no comments for Property Revision in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Revision
        {
            get
            {
                return this._Revision;
            }
            set
            {
                this.OnRevisionChanging(value);
                this._Revision = value;
                this.OnRevisionChanged();
                this.OnPropertyChanged("Revision");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Revision;
        partial void OnRevisionChanging(int value);
        partial void OnRevisionChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Priority;
        partial void OnPriorityChanging(string value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property Severity in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Severity
        {
            get
            {
                return this._Severity;
            }
            set
            {
                this.OnSeverityChanging(value);
                this._Severity = value;
                this.OnSeverityChanged();
                this.OnPropertyChanged("Severity");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Severity;
        partial void OnSeverityChanging(string value);
        partial void OnSeverityChanged();
        /// <summary>
        /// There are no comments for Property StackRank in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StackRank
        {
            get
            {
                return this._StackRank;
            }
            set
            {
                this.OnStackRankChanging(value);
                this._StackRank = value;
                this.OnStackRankChanged();
                this.OnPropertyChanged("StackRank");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StackRank;
        partial void OnStackRankChanging(string value);
        partial void OnStackRankChanged();
        /// <summary>
        /// There are no comments for Property Project in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Project
        {
            get
            {
                return this._Project;
            }
            set
            {
                this.OnProjectChanging(value);
                this._Project = value;
                this.OnProjectChanged();
                this.OnPropertyChanged("Project");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Project;
        partial void OnProjectChanging(string value);
        partial void OnProjectChanged();
        /// <summary>
        /// There are no comments for Property AssignedTo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AssignedTo
        {
            get
            {
                return this._AssignedTo;
            }
            set
            {
                this.OnAssignedToChanging(value);
                this._AssignedTo = value;
                this.OnAssignedToChanged();
                this.OnPropertyChanged("AssignedTo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AssignedTo;
        partial void OnAssignedToChanging(string value);
        partial void OnAssignedToChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ChangedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ChangedDate
        {
            get
            {
                return this._ChangedDate;
            }
            set
            {
                this.OnChangedDateChanging(value);
                this._ChangedDate = value;
                this.OnChangedDateChanged();
                this.OnPropertyChanged("ChangedDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ChangedDate;
        partial void OnChangedDateChanging(global::System.DateTime value);
        partial void OnChangedDateChanged();
        /// <summary>
        /// There are no comments for Property ChangedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChangedBy
        {
            get
            {
                return this._ChangedBy;
            }
            set
            {
                this.OnChangedByChanging(value);
                this._ChangedBy = value;
                this.OnChangedByChanged();
                this.OnPropertyChanged("ChangedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChangedBy;
        partial void OnChangedByChanging(string value);
        partial void OnChangedByChanged();
        /// <summary>
        /// There are no comments for Property ResolvedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResolvedBy
        {
            get
            {
                return this._ResolvedBy;
            }
            set
            {
                this.OnResolvedByChanging(value);
                this._ResolvedBy = value;
                this.OnResolvedByChanged();
                this.OnPropertyChanged("ResolvedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResolvedBy;
        partial void OnResolvedByChanging(string value);
        partial void OnResolvedByChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Reason in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reason
        {
            get
            {
                return this._Reason;
            }
            set
            {
                this.OnReasonChanging(value);
                this._Reason = value;
                this.OnReasonChanged();
                this.OnPropertyChanged("Reason");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reason;
        partial void OnReasonChanging(string value);
        partial void OnReasonChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ReproSteps in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ReproSteps
        {
            get
            {
                return this._ReproSteps;
            }
            set
            {
                this.OnReproStepsChanging(value);
                this._ReproSteps = value;
                this.OnReproStepsChanged();
                this.OnPropertyChanged("ReproSteps");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ReproSteps;
        partial void OnReproStepsChanging(string value);
        partial void OnReproStepsChanged();
        /// <summary>
        /// There are no comments for Property FoundInBuild in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FoundInBuild
        {
            get
            {
                return this._FoundInBuild;
            }
            set
            {
                this.OnFoundInBuildChanging(value);
                this._FoundInBuild = value;
                this.OnFoundInBuildChanged();
                this.OnPropertyChanged("FoundInBuild");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FoundInBuild;
        partial void OnFoundInBuildChanging(string value);
        partial void OnFoundInBuildChanged();
        /// <summary>
        /// There are no comments for Property IntegratedInBuild in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IntegratedInBuild
        {
            get
            {
                return this._IntegratedInBuild;
            }
            set
            {
                this.OnIntegratedInBuildChanging(value);
                this._IntegratedInBuild = value;
                this.OnIntegratedInBuildChanged();
                this.OnPropertyChanged("IntegratedInBuild");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IntegratedInBuild;
        partial void OnIntegratedInBuildChanging(string value);
        partial void OnIntegratedInBuildChanged();
        /// <summary>
        /// There are no comments for Property WebEditorUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WebEditorUrl
        {
            get
            {
                return this._WebEditorUrl;
            }
            set
            {
                this.OnWebEditorUrlChanging(value);
                this._WebEditorUrl = value;
                this.OnWebEditorUrlChanged();
                this.OnPropertyChanged("WebEditorUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WebEditorUrl;
        partial void OnWebEditorUrlChanging(string value);
        partial void OnWebEditorUrlChanged();
        /// <summary>
        /// There are no comments for Attachments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Attachment> Attachments
        {
            get
            {
                return this._Attachments;
            }
            set
            {
                this._Attachments = value;
                this.OnPropertyChanged("Attachments");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Attachment> _Attachments = new global::System.Data.Services.Client.DataServiceCollection<Attachment>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
