// ----------------------------------------------------------------------------------
// Microsoft Developer & Platform Evangelism
// 
// Copyright (c) Microsoft Corporation. All rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
// ----------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: TFSModel.cs
// Generation date: 03/11/2010 08:13:31 p.m.
namespace Microsoft.Samples.DPE.ODataTFS.Model.Entities
{
    /// <summary>
    /// There are no comments for Microsoft.Samples.DPE.ODataTFS.Model.Entities.Build in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Definition
    /// Number
    /// Project
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Builds")]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Number", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Status", System.Data.Services.Common.SyndicationItemProperty.Summary, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("LastChangedOn", System.Data.Services.Common.SyndicationItemProperty.Updated, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Definition", "Number", "Project")]
    public partial class Build : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Build object.
        /// </summary>
        /// <param name="project">Initial value of Project.</param>
        /// <param name="definition">Initial value of Definition.</param>
        /// <param name="number">Initial value of Number.</param>
        /// <param name="startTime">Initial value of StartTime.</param>
        /// <param name="finishTime">Initial value of FinishTime.</param>
        /// <param name="lastChangedOn">Initial value of LastChangedOn.</param>
        /// <param name="buildFinished">Initial value of BuildFinished.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Build CreateBuild(string project, string definition, string number, global::System.DateTime startTime, global::System.DateTime finishTime, global::System.DateTime lastChangedOn, bool buildFinished)
        {
            Build build = new Build();
            build.Project = project;
            build.Definition = definition;
            build.Number = number;
            build.StartTime = startTime;
            build.FinishTime = finishTime;
            build.LastChangedOn = lastChangedOn;
            build.BuildFinished = buildFinished;
            return build;
        }
        /// <summary>
        /// There are no comments for Property Project in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Project
        {
            get
            {
                return this._Project;
            }
            set
            {
                this.OnProjectChanging(value);
                this._Project = value;
                this.OnProjectChanged();
                this.OnPropertyChanged("Project");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Project;
        partial void OnProjectChanging(string value);
        partial void OnProjectChanged();
        /// <summary>
        /// There are no comments for Property Definition in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Definition
        {
            get
            {
                return this._Definition;
            }
            set
            {
                this.OnDefinitionChanging(value);
                this._Definition = value;
                this.OnDefinitionChanged();
                this.OnPropertyChanged("Definition");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Definition;
        partial void OnDefinitionChanging(string value);
        partial void OnDefinitionChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Reason in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reason
        {
            get
            {
                return this._Reason;
            }
            set
            {
                this.OnReasonChanging(value);
                this._Reason = value;
                this.OnReasonChanged();
                this.OnPropertyChanged("Reason");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reason;
        partial void OnReasonChanging(string value);
        partial void OnReasonChanged();
        /// <summary>
        /// There are no comments for Property Quality in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Quality
        {
            get
            {
                return this._Quality;
            }
            set
            {
                this.OnQualityChanging(value);
                this._Quality = value;
                this.OnQualityChanged();
                this.OnPropertyChanged("Quality");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Quality;
        partial void OnQualityChanging(string value);
        partial void OnQualityChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property RequestedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequestedBy
        {
            get
            {
                return this._RequestedBy;
            }
            set
            {
                this.OnRequestedByChanging(value);
                this._RequestedBy = value;
                this.OnRequestedByChanged();
                this.OnPropertyChanged("RequestedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequestedBy;
        partial void OnRequestedByChanging(string value);
        partial void OnRequestedByChanged();
        /// <summary>
        /// There are no comments for Property RequestedFor in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequestedFor
        {
            get
            {
                return this._RequestedFor;
            }
            set
            {
                this.OnRequestedForChanging(value);
                this._RequestedFor = value;
                this.OnRequestedForChanged();
                this.OnPropertyChanged("RequestedFor");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequestedFor;
        partial void OnRequestedForChanging(string value);
        partial void OnRequestedForChanged();
        /// <summary>
        /// There are no comments for Property LastChangedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastChangedBy
        {
            get
            {
                return this._LastChangedBy;
            }
            set
            {
                this.OnLastChangedByChanging(value);
                this._LastChangedBy = value;
                this.OnLastChangedByChanged();
                this.OnPropertyChanged("LastChangedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastChangedBy;
        partial void OnLastChangedByChanging(string value);
        partial void OnLastChangedByChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this._StartTime = value;
                this.OnStartTimeChanged();
                this.OnPropertyChanged("StartTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property FinishTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FinishTime
        {
            get
            {
                return this._FinishTime;
            }
            set
            {
                this.OnFinishTimeChanging(value);
                this._FinishTime = value;
                this.OnFinishTimeChanged();
                this.OnPropertyChanged("FinishTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FinishTime;
        partial void OnFinishTimeChanging(global::System.DateTime value);
        partial void OnFinishTimeChanged();
        /// <summary>
        /// There are no comments for Property LastChangedOn in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastChangedOn
        {
            get
            {
                return this._LastChangedOn;
            }
            set
            {
                this.OnLastChangedOnChanging(value);
                this._LastChangedOn = value;
                this.OnLastChangedOnChanged();
                this.OnPropertyChanged("LastChangedOn");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastChangedOn;
        partial void OnLastChangedOnChanging(global::System.DateTime value);
        partial void OnLastChangedOnChanged();
        /// <summary>
        /// There are no comments for Property BuildFinished in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool BuildFinished
        {
            get
            {
                return this._BuildFinished;
            }
            set
            {
                this.OnBuildFinishedChanging(value);
                this._BuildFinished = value;
                this.OnBuildFinishedChanged();
                this.OnPropertyChanged("BuildFinished");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _BuildFinished;
        partial void OnBuildFinishedChanging(bool value);
        partial void OnBuildFinishedChanged();
        /// <summary>
        /// There are no comments for Property DropLocation in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DropLocation
        {
            get
            {
                return this._DropLocation;
            }
            set
            {
                this.OnDropLocationChanging(value);
                this._DropLocation = value;
                this.OnDropLocationChanged();
                this.OnPropertyChanged("DropLocation");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DropLocation;
        partial void OnDropLocationChanging(string value);
        partial void OnDropLocationChanged();
        /// <summary>
        /// There are no comments for Property Errors in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Errors
        {
            get
            {
                return this._Errors;
            }
            set
            {
                this.OnErrorsChanging(value);
                this._Errors = value;
                this.OnErrorsChanged();
                this.OnPropertyChanged("Errors");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Errors;
        partial void OnErrorsChanging(string value);
        partial void OnErrorsChanged();
        /// <summary>
        /// There are no comments for Property Warnings in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Warnings
        {
            get
            {
                return this._Warnings;
            }
            set
            {
                this.OnWarningsChanging(value);
                this._Warnings = value;
                this.OnWarningsChanged();
                this.OnPropertyChanged("Warnings");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Warnings;
        partial void OnWarningsChanging(string value);
        partial void OnWarningsChanged();
        /// <summary>
        /// There are no comments for WorkItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<WorkItem> WorkItems
        {
            get
            {
                return this._WorkItems;
            }
            set
            {
                this._WorkItems = value;
                this.OnPropertyChanged("WorkItems");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<WorkItem> _WorkItems = new global::System.Data.Services.Client.DataServiceCollection<WorkItem>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Changesets in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Changeset> Changesets
        {
            get
            {
                return this._Changesets;
            }
            set
            {
                this._Changesets = value;
                this.OnPropertyChanged("Changesets");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Changeset> _Changesets = new global::System.Data.Services.Client.DataServiceCollection<Changeset>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
